#!/usr/bin/env python3

"""
Post-processing visualization script for path controller data
Reads CSV files generated by path_controller.py and creates plots
"""

import csv
import argparse
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
from collections import defaultdict
import os


def load_csv_data(filename: str) -> dict:
    """Load CSV data into structured format."""
    data = defaultdict(list)
    waypoints = []  # Store waypoints separately (drone_id = -1)
    metadata = {}  # Store path metadata
    
    with open(filename, 'r') as f:
        lines = f.readlines()
        
    # Parse metadata lines (comments starting with #)
    i = 0
    while i < len(lines) and lines[i].strip().startswith('#'):
        line = lines[i].strip()
        parts = line.split(',')
        if len(parts) >= 2:
            key = parts[0].replace('#', '').strip()
            value = parts[1].strip()
            if key == 'path_type':
                metadata['path_type'] = value
            elif key == 'speed':
                metadata['speed'] = float(value)
            elif key == 'num_drones':
                metadata['num_drones'] = int(value)
            elif key == 'square_size':
                metadata['square_size'] = float(value)
            elif key == 'circle_radius':
                metadata['circle_radius'] = float(value)
            elif key == 'figure8_size':
                metadata['figure8_size'] = float(value)
        i += 1
    
    # Skip "End metadata" line if present
    if i < len(lines) and lines[i].strip().startswith('#'):
        i += 1
    
    # Now read the actual CSV data (from header line onwards)
    reader = csv.DictReader(lines[i:])
    for row in reader:
        drone_id = int(row['drone_id'])
        entry = {
            'timestamp': float(row['timestamp']),
            'x': float(row['x']),
            'y': float(row['y']),
            'z': float(row['z']),
            'waypoint_idx': int(row['waypoint_idx'])
        }
        
        if drone_id == -1:
            # This is a waypoint
            waypoints.append(entry)
        else:
            # This is a drone position
            data[drone_id].append(entry)
    
    # Store waypoints in data dict with key -1
    if waypoints:
        data[-1] = waypoints
    
    # Store metadata with key 'metadata'
    data['metadata'] = metadata
    
    return data


def calculate_separation_distances(data: dict, num_drones: int) -> dict:
    """Calculate separation distances between leader and each follower."""
    separations = defaultdict(list)
    
    leader_id = 0
    if leader_id not in data or len(data[leader_id]) == 0:
        return separations
    
    # Use leader's timestamps as reference - iterate through leader entries
    for leader_entry in data[leader_id]:
        timestamp = leader_entry['timestamp']
        leader_pos = (leader_entry['x'], leader_entry['y'], leader_entry['z'])
        
        # Calculate distance from leader to each follower
        for follower_id in range(1, num_drones):  # Start from 1 (skip leader)
            if follower_id in data:
                # Find closest timestamp entry for this follower
                closest_entry = min(data[follower_id], 
                                  key=lambda x: abs(x['timestamp'] - timestamp))
                if abs(closest_entry['timestamp'] - timestamp) < 0.1:
                    follower_pos = (closest_entry['x'], closest_entry['y'], closest_entry['z'])
                    dx = leader_pos[0] - follower_pos[0]
                    dy = leader_pos[1] - follower_pos[1]
                    dz = leader_pos[2] - follower_pos[2]
                    distance = np.sqrt(dx*dx + dy*dy + dz*dz)
                    separations[(leader_id, follower_id)].append(distance)
                else:
                    separations[(leader_id, follower_id)].append(np.nan)
            else:
                separations[(leader_id, follower_id)].append(np.nan)
    
    return separations


def calculate_formation_error(data: dict, leader_id: int = 0) -> dict:
    """Calculate formation error (deviation from desired formation)."""
    # Desired formation offsets (from C++ code)
    formation_offsets = {
        0: (0.0, 0.0, 0.0),      # Leader
        1: (-3.0, -3.0, 0.0),     # Follower 1
        2: (3.0, 3.0, 0.0),      # Follower 2
        3: (-3.0, 3.0, 0.0),      # Follower 3
        4: (3.0, -3.0, 0.0),     # Follower 4
    }
    
    errors = defaultdict(list)
    timestamps = []
    
    if leader_id not in data:
        return errors, timestamps
    
    for entry in data[leader_id]:
        timestamp = entry['timestamp']
        timestamps.append(timestamp)
        leader_pos = (entry['x'], entry['y'], entry['z'])
        
        for drone_id in range(len(formation_offsets)):
            if drone_id == leader_id:
                errors[drone_id].append(0.0)
                continue
            
            if drone_id in data:
                # Find closest timestamp entry
                closest_entry = min(data[drone_id], 
                                  key=lambda x: abs(x['timestamp'] - timestamp))
                if abs(closest_entry['timestamp'] - timestamp) < 0.1:
                    actual_pos = (closest_entry['x'], closest_entry['y'], closest_entry['z'])
                    desired_offset = formation_offsets[drone_id]
                    desired_pos = (
                        leader_pos[0] + desired_offset[0],
                        leader_pos[1] + desired_offset[1],
                        leader_pos[2] + desired_offset[2]
                    )
                    
                    dx = actual_pos[0] - desired_pos[0]
                    dy = actual_pos[1] - desired_pos[1]
                    dz = actual_pos[2] - desired_pos[2]
                    error = np.sqrt(dx*dx + dy*dy + dz*dz)
                    errors[drone_id].append(error)
                else:
                    errors[drone_id].append(np.nan)
            else:
                errors[drone_id].append(np.nan)
    
    return errors, timestamps


def plot_paths_2d(data: dict, output_file: str = None):
    """Plot 2D top-down view of all drone paths."""
    fig, ax = plt.subplots(figsize=(12, 10))
    
    colors = ['red', 'blue', 'green', 'orange', 'purple']
    labels = ['Leader', 'Follower 1', 'Follower 2', 'Follower 3', 'Follower 4']
    
    # Get path metadata for title
    path_type = data.get('metadata', {}).get('path_type', 'unknown')
    
    # Plot planned path (waypoints) first
    if -1 in data and len(data[-1]) > 0:
        waypoints = data[-1]
        # Sort by waypoint_idx to ensure correct order
        waypoints = sorted(waypoints, key=lambda w: w['waypoint_idx'])
        wp_x = [w['x'] for w in waypoints]
        wp_y = [w['y'] for w in waypoints]
        ax.plot(wp_x, wp_y, color='black', linestyle='--', linewidth=2.5, 
               label='Planned Path', alpha=0.8, zorder=1)
        # Mark waypoints
        ax.scatter(wp_x, wp_y, color='black', s=150, marker='*', 
                  edgecolors='white', linewidths=1.5, zorder=6, label='Waypoints')
    
    # Plot drone paths (filter out waypoints and metadata before sorting)
    drone_ids = [d for d in data.keys() if isinstance(d, int) and d != -1 and d != 'metadata']
    
    # Print info about which drones are being plotted
    print(f"\nPlotting paths for {len(drone_ids)} drones: {sorted(drone_ids)}")
    
    for drone_id in sorted(drone_ids):
        if len(data[drone_id]) == 0:
            print(f"  Warning: Drone {drone_id} has no data")
            continue
        
        x = [d['x'] for d in data[drone_id]]
        y = [d['y'] for d in data[drone_id]]
        
        # Print start position for debugging
        if len(x) > 0:
            print(f"  Drone {drone_id} start position: ({x[0]:.2f}, {y[0]:.2f})")
        
        color = colors[drone_id % len(colors)]
        label = labels[drone_id] if drone_id < len(labels) else f'Drone {drone_id}'
        
        ax.plot(x, y, color=color, label=label, linewidth=2, alpha=0.7, zorder=2)
        # Mark start position
        if len(x) > 0:
            ax.scatter(x[0], y[0], color=color, s=100, marker='o', 
                      edgecolors='black', linewidths=2, zorder=5)
        # Mark end position
        if len(x) > 0:
            ax.scatter(x[-1], y[-1], color=color, s=100, marker='s', 
                      edgecolors='black', linewidths=2, zorder=5)
    
    ax.set_xlabel('X Position (m)', fontsize=12)
    ax.set_ylabel('Y Position (m)', fontsize=12)
    title = f'2D Top-Down View: {path_type.upper()} Path'
    ax.set_title(title, fontsize=14, fontweight='bold')
    ax.legend(loc='best')
    ax.grid(True, alpha=0.3)
    ax.set_aspect('equal', adjustable='box')
    
    plt.tight_layout()
    if output_file:
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        print(f"Saved 2D plot to {output_file}")
    # Note: plt.show() is called by main() if needed


def plot_paths_3d(data: dict, output_file: str = None):
    """Plot 3D view of all drone paths."""
    fig = plt.figure(figsize=(12, 10))
    ax = fig.add_subplot(111, projection='3d')
    
    colors = ['red', 'blue', 'green', 'orange', 'purple']
    labels = ['Leader', 'Follower 1', 'Follower 2', 'Follower 3', 'Follower 4']
    
    # Get path metadata for title
    path_type = data.get('metadata', {}).get('path_type', 'unknown')
    
    # Collect all z values to determine flight altitude and fix z-axis range
    all_z_values = []
    
    # Plot planned path (waypoints) first
    if -1 in data and len(data[-1]) > 0:
        waypoints = data[-1]
        # Sort by waypoint_idx to ensure correct order
        waypoints = sorted(waypoints, key=lambda w: w['waypoint_idx'])
        wp_x = [w['x'] for w in waypoints]
        wp_y = [w['y'] for w in waypoints]
        wp_z = [-w['z'] for w in waypoints]  # Flip z: higher negative = higher from ground
        all_z_values.extend(wp_z)
        ax.plot(wp_x, wp_y, wp_z, color='black', linestyle='--', linewidth=2.5, 
               label='Planned Path', alpha=0.8, zorder=1)
        # Mark waypoints
        ax.scatter(wp_x, wp_y, wp_z, color='black', s=150, marker='*', 
                  edgecolors='white', linewidths=1.5, zorder=6, label='Waypoints')
    
    # Plot drone paths (filter out waypoints and metadata before sorting)
    drone_ids = [d for d in data.keys() if d != -1 and d != 'metadata']
    for drone_id in sorted(drone_ids):
        if len(data[drone_id]) == 0:
            continue
        
        x = [d['x'] for d in data[drone_id]]
        y = [d['y'] for d in data[drone_id]]
        z = [-d['z'] for d in data[drone_id]]  # Flip z: higher negative = higher from ground
        all_z_values.extend(z)
        
        color = colors[drone_id % len(colors)]
        label = labels[drone_id] if drone_id < len(labels) else f'Drone {drone_id}'
        
        ax.plot(x, y, z, color=color, label=label, linewidth=2, alpha=0.7, zorder=2)
        # Mark start position
        if len(x) > 0:
            ax.scatter(x[0], y[0], z[0], color=color, s=100, marker='o', 
                      edgecolors='black', linewidths=2, zorder=5)
    
    # Set z-axis range to 5 meters from the average flight altitude
    if all_z_values:
        avg_z = np.mean(all_z_values)
        z_min = avg_z - 2.5  # 2.5m below average
        z_max = avg_z + 2.5  # 2.5m above average (total 5m range)
        ax.set_zlim(z_min, z_max)
    
    ax.set_xlabel('X Position (m)', fontsize=12)
    ax.set_ylabel('Y Position (m)', fontsize=12)
    ax.set_zlabel('Height (m)', fontsize=12)  # Changed label since we flipped z
    title = f'3D View: {path_type.upper()} Path'
    ax.set_title(title, fontsize=14, fontweight='bold')
    ax.legend(loc='best')
    
    plt.tight_layout()
    if output_file:
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        print(f"Saved 3D plot to {output_file}")
    # Note: plt.show() is called by main() if needed


def plot_separation_distances(separations: dict, output_file: str = None):
    """Plot separation distances between leader and followers over time."""
    fig, ax = plt.subplots(figsize=(12, 6))
    
    colors = ['blue', 'green', 'orange', 'purple']
    labels = ['Follower 1', 'Follower 2', 'Follower 3', 'Follower 4']
    
    for pair, distances in separations.items():
        if len(distances) == 0:
            continue
        
        # Only plot leader (0) to follower pairs
        if pair[0] != 0:
            continue
        
        follower_id = pair[1]
        times = np.arange(len(distances)) * 0.02  # Assuming 50Hz logging
        valid_distances = [d for d in distances if not np.isnan(d)]
        valid_times = [times[i] for i, d in enumerate(distances) if not np.isnan(d)]
        
        if len(valid_distances) > 0:
            color = colors[(follower_id - 1) % len(colors)]
            label = labels[follower_id - 1] if (follower_id - 1) < len(labels) else f'Follower {follower_id}'
            ax.plot(valid_times, valid_distances, color=color, label=label, linewidth=2, alpha=0.7)
    
    # Add minimum safe distance line
    ax.axhline(y=1.5, color='red', linestyle='--', linewidth=2, 
              label='Min Safe Distance (1.5m)', alpha=0.7)
    
    ax.set_xlabel('Time (s)', fontsize=12)
    ax.set_ylabel('Separation Distance (m)', fontsize=12)
    ax.set_title('Separation Distances: Leader to Followers', fontsize=14, fontweight='bold')
    ax.legend(loc='best')
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    if output_file:
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        print(f"Saved separation plot to {output_file}")
    else:
        plt.show()


def plot_formation_error(errors: dict, timestamps: list, output_file: str = None):
    """Plot formation error over time."""
    fig, ax = plt.subplots(figsize=(12, 6))
    
    colors = ['blue', 'green', 'orange', 'purple']
    labels = ['Follower 1', 'Follower 2', 'Follower 3', 'Follower 4']
    
    for drone_id in sorted(errors.keys()):
        if drone_id == 0:  # Skip leader
            continue
        
        error_values = errors[drone_id]
        valid_errors = [e for e, t in zip(error_values, timestamps) if not np.isnan(e)]
        valid_times = [t for e, t in zip(error_values, timestamps) if not np.isnan(e)]
        
        if len(valid_errors) > 0:
            color = colors[(drone_id - 1) % len(colors)]
            label = labels[drone_id - 1] if (drone_id - 1) < len(labels) else f'Follower {drone_id}'
            ax.plot(valid_times, valid_errors, color=color, label=label, linewidth=2, alpha=0.7)
    
    # Set constant y-axis range from 0 to 20 meters
    ax.set_ylim(0, 20)
    
    ax.set_xlabel('Time (s)', fontsize=12)
    ax.set_ylabel('Formation Error (m)', fontsize=12)
    ax.set_title('Formation Error (Deviation from Desired Position)', fontsize=14, fontweight='bold')
    ax.legend(loc='best')
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    if output_file:
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        print(f"Saved formation error plot to {output_file}")
    # Note: plt.show() is called by main() if needed


def print_statistics(data: dict, separations: dict, errors: dict):
    """Print summary statistics."""
    print("\n" + "="*60)
    print("PATH ANALYSIS STATISTICS")
    print("="*60)
    
    # Minimum separation distances
    print("\nMinimum Separation Distances (Leader to Followers):")
    min_separations = {}
    for pair, distances in separations.items():
        if pair[0] != 0:  # Only show leader-to-follower
            continue
        valid_distances = [d for d in distances if not np.isnan(d)]
        if len(valid_distances) > 0:
            min_sep = min(valid_distances)
            follower_id = pair[1]
            min_separations[pair] = min_sep
            print(f"  Leader - Follower {follower_id}: {min_sep:.3f} m")
    
    overall_min = min(min_separations.values()) if min_separations else 0.0
    print(f"\n  Overall Minimum: {overall_min:.3f} m")
    
    # Formation errors
    print("\nAverage Formation Errors:")
    for drone_id in sorted(errors.keys()):
        if drone_id == 0:
            continue
        error_values = [e for e in errors[drone_id] if not np.isnan(e)]
        if len(error_values) > 0:
            avg_error = np.mean(error_values)
            max_error = np.max(error_values)
            print(f"  Follower {drone_id}: Avg={avg_error:.3f} m, Max={max_error:.3f} m")
    
    # Path completion
    if 0 in data and len(data[0]) > 0:
        duration = data[0][-1]['timestamp'] - data[0][0]['timestamp']
        print(f"\nPath Duration: {duration:.2f} seconds")
        print(f"Total Data Points: {len(data[0])}")
    
    print("="*60 + "\n")


def main():
    parser = argparse.ArgumentParser(description='Visualize path controller data')
    parser.add_argument('csv_file', type=str, help='CSV file to visualize')
    parser.add_argument('--num_drones', type=int, default=5, help='Number of drones')
    parser.add_argument('--output_dir', type=str, default='.', help='Output directory for plots')
    parser.add_argument('--no-show', action='store_true', help='Don\'t display plots, only save')
    
    args = parser.parse_args()
    
    if not os.path.exists(args.csv_file):
        print(f"Error: CSV file not found: {args.csv_file}")
        return
    
    print(f"Loading data from {args.csv_file}...")
    data = load_csv_data(args.csv_file)
    
    print("Calculating metrics...")
    separations = calculate_separation_distances(data, args.num_drones)
    errors, timestamps = calculate_formation_error(data, leader_id=0)
    
    print_statistics(data, separations, errors)
    
    # Generate base filename
    base_name = os.path.splitext(os.path.basename(args.csv_file))[0]
    
    # Ensure output directory exists
    os.makedirs(args.output_dir, exist_ok=True)
    
    # Create plots
    print("Generating plots...")
    print(f"Output directory: {args.output_dir}")
    
    plot_2d_file = os.path.join(args.output_dir, f"{base_name}_2d.png")
    plot_paths_2d(data, plot_2d_file)
    if not args.no_show:
        plt.show()  # Show plot if not in no-show mode
    plt.close()  # Close figure after saving/showing
    
    plot_3d_file = os.path.join(args.output_dir, f"{base_name}_3d.png")
    plot_paths_3d(data, plot_3d_file)
    if not args.no_show:
        plt.show()
    plt.close()
    
    plot_sep_file = os.path.join(args.output_dir, f"{base_name}_separation.png")
    plot_separation_distances(separations, plot_sep_file)
    if not args.no_show:
        plt.show()
    plt.close()
    
    plot_err_file = os.path.join(args.output_dir, f"{base_name}_formation_error.png")
    plot_formation_error(errors, timestamps, plot_err_file)
    if not args.no_show:
        plt.show()
    plt.close()
    
    print("\nVisualization complete!")


if __name__ == '__main__':
    main()

